name: Windows Build

on: [push, pull_request]

jobs:
  build-bam:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        include:
        - name: "Windows x64"
          os: windows-latest
          cmake-args: -G "Visual Studio 16 2019" -A x64
          package-file: ninslash-win64.zip
          package-full-file: ninslash-win64-full.zip

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Checkout bam
      uses: actions/checkout@v2
      with:
        repository: matricks/bam
        ref: 8cd08744c37666830d439ab54016c9d228c63b68
        path: ./bam

    - name: Prepare Windows
      if: contains(matrix.os, 'windows')
      run: |
        cd bam
        ./make_win64_msvc.bat
    - name: Build in debug mode
      run: ./bam/bam conf=debug all
    - name: Test debug
      run: ./ninslash_srv_d shutdown

    - name: Build in release mode
      run: ./bam/bam conf=release all
    - name: Test release
      run: ./ninslash_srv shutdown
